---
title: "us_tilapia_imports"
author: "Jake Eisaguirre"
date: "8/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

```{r}

tilapia_data <- read_csv(here("data", "us_tilapia_imports.csv"))
view(tilapia_data)
summary(tilapia_data)
names(tilapia_data)


```

```{r}

new_tilapia_data <- pivot_longer(tilapia_data, -country, names_to = "year", values_to = "tilapia")

class(tilapia_data$year)
class(tilapia_data$value)

the_tilapia_data <- new_tilapia_data %>% 
  mutate(year = (as.numeric(year)))

yearly_tilapia_tot <- group_by(the_tilapia_data, year) %>%
  summarise(tilapia_tot = sum(tilapia, na.rm = TRUE))

ggplot(yearly_tilapia_tot, aes(x = year, y = tilapia_tot)) +
  geom_line() + labs(x = "Year", y = "Tilapia Imported (thousands of pound^-1)")

ggsave(here("figs", "yearly_tilapia_tot.png"))

```

```{r}

select_imports <- the_tilapia_data %>% 
  filter(country %in% c("Ecuador", "Honduras", "Costa Rica", "Mexico"), na.rm = TRUE)

ggplot(select_imports, aes(x = year, y = tilapia, color = country)) +
  geom_line() + 
  labs(y = "Tilapia (thousands of pounds^-1)", x = "Year", title = "Tilapia Exports") + 
  theme_classic() +
  scale_color_manual(values = c("Ecuador" = "pink", "Honduras" = "purple" , "Costa Rica" = "orange", "Mexico" = "yellow"))

#scale_colour_viridis_d()

ggsave(here("figs", "select_countries.jpg"))
```

